### ISSUE TITLE
Question: Custom format for package logger

### ISSUE THREAD

**Issue by mllg** [s-fleck/lgr#15]
Your package looks really promising, I'm currently testing if we should prefer `lgr` over `logger` for https://github.com/mlr-org/mlr3.

Creating a package logger is nicely explained in your vignette. However, I'm unsure how to proceed if I want to have a custom format for log messages (background: we are automatically deploying our docs as HTML via pkgdown after each commit, and I don't want time stamps to be included in all the examples and vignettes).

I came up with the following lines in my `.onLoad`.
```r
  logger = lgr::Logger$new(name = "mlr3", appenders = list(console = lgr::AppenderConsole$new()), propagate = FALSE)
  logger$appenders$console$set_layout(lgr::LayoutFormat$new(fmt = "[%L] %m"))
  assign(...)
```
This already worked reasonably (except that %L inserts a trailing whitespace). However, I'm unsure how the user now configures this logger. Without propagating to the root logger, I would have to export the logger object in my package, right? 

Is there a way to propagate to the root logger with a different format?

**Comment by s-fleck** [comment]
Thanks for the interest. 

I've been using lgr in a big project myself and there will be a few changes to how loggers are created and configured for the next version that will solve your problem. The changes are already in the github version, but not yet fully documented I think.

The recommended way is now

```
lg <- get_logger("mlr3")
lg$add_appender(.....)
assign(...)
```

Loggers created with get_logger at stored globally, so the user can just do the following without you having to export the logger:

```
lg <- get_logger("mlr3")
lg$set_appender(...)

# or even just

get_logger("mlr3")$set_appender
```

This is how python logging does it, and though it might seem a bit strange at first it solves a lot of problems.

**Comment by s-fleck** [comment]
Oh sorry I also missed a part of your question.

I'll try to roll it out from the Beginning:

You should probably not configure your package logger at all. The idea is that the user can configure the loggers on a per-package basis, though commonly the user will only configure the formatting of the root logger, and just switch the package loggers on and off (by modifying the threshold or setting propagate to false).

For the vignette the cleanest way would just be to configure the console appender of the root logger to your format.
I have to confess I don't have a solution for the examples. This is a valid point and I wil think on it.

**Comment by s-fleck** [comment]
I thought about this for a while, and came to the conclusion that this does not fit in the concept of lgr. Loggers should just dispatch the content of the log event to their parents, and how it is presented (formatting, etc) should be left to the package user. While custom per-package formatting is certainly possible via per-package Appenders, it is really not the recommended way to use logger.

**Comment by s-fleck** [comment]
I thought about this for a while, and came to the conclusion that this does not fit in the concept of lgr. Loggers should just dispatch the content of the log event to their parents, and how it is presented (formatting, etc) should be left to the package user. While custom per-package formatting is certainly possible via per-package Appenders, it is really not the recommended way to use logger.

**Comment by dselivanov** [comment]
> Loggers should just dispatch the content of the log event to their parents, and how it is presented (formatting, etc) should be left to the package user. While custom per-package formatting is certainly possible via per-package Appenders, it is really not the recommended way to use logger.

I don't quite agree with that. For me as pkg author it makes sense to define reasonable default formatter and default appender and leave a possibility to change these defaults to a user. 

For example in a package I would define logger as following:

```r
.onLoad = function(libname, pkgname) {
  logger = lgr::Logger$new(name = 'PKGNAME')
  logger$add_appender(lgr::AppenderConsole$new())
  logger$set_threshold('info')
  assign("lg", logger, envir = parent.env(environment()))
}
```

User would load the package and will be able to change defaults if needed:
```r
library('PKGNAME')
lg = lgr::get_logger('PKGNAME')
lg$set_threshold('warn')
lg$appenders[[1]]$set_layout(layout = lgr::LayoutJson$new())
```

However as of now this line
```r
lg = lgr::get_logger('PKGNAME')
```
Doesn't return package logger, but I believe returns new one. Package logger is not exported and is accessible by `PKGNAME:::lg`.

**Comment by s-fleck** [comment]
> I don't quite agree with that. For me as pkg author it makes sense to define reasonable default formatter and default appender and leave a possibility to change these defaults to a user.

I agree that it would be useful, I just can't figure out how to make that work with lgr. Obviously you could use an Appender with custom formatting and set `propagate = FALSE`. This is in principle the same approach that you have to take with other logging packages if you want to have custom formatting for your package.

However, this defeats the idea of one central logging place for the user to configure. With lgr the assumption is that you have several sources (f.e packages) that dispatch events to the root logger, and it would be weird if all of them have different custom formatting.

To your problem:
You are nearly doing the right thing, but you should **not use Logger$new anymore**. just change your code to:

```
.onLoad = function(libname, pkgname) {
  logger = lgr::get_logger("PKGNAME")  # first call to get_logger initializes the logger
  logger$add_appender(lgr::AppenderConsole$new())
  logger$set_threshold('info')
  assign("lg", logger, envir = parent.env(environment()))
}
```

**Comment by dselivanov** [comment]
> not use Logger$new anymore

Thanks for clarification, works perfectly now. I think this class should not be exported then?

**Comment by s-fleck** [comment]
yes and no. it should not be instantiated by the end user, but if you are a package author you can create your own subclass (like `LoggerGlue`). if I don't export it you lose this ability. for the same reason a few "abstract" appenders that are useless on their own are also exported.
