### ISSUE TITLE
JSON logging

### ISSUE THREAD

**Issue by dselivanov** [s-fleck/lgr#17]
Hi Stefan. Thanks for the package. I just wanted to provide some feedback. 

- I really like that `lgr` doesn't hide R6
- I found that usage of some appenders and layouts/formatters little bit confusing - will clarify below.

As for me there should be clear separation between log destinations and log formatters (and it seems you generally share same idea). And from this perspective `AppenderJson` looks a little bit weird - it mixes both file sink and JSON formatting. 

Sometimes I would like to have structured logging in order to be able to have `msg` in a log not as a plain string, but an easy to parse object. So it would be nice to have ability to specify on how to "translate" R's message into logging record. For example with JSON layout we can serialize R objects into json objects (and have fully machine-readable  logs):

Current behaviour:
```r
library(lgr)
lgr$appenders$console$set_layout(layout = LayoutJson$new())
lgr$info(list(a = 'b'))
# currently produces
# {"level":400,"timestamp":"2019-03-12 15:44:40","logger":"root","caller":"(shell)","msg":"b"}
```

Would like to have:
```r
# {"level":400,"timestamp":"2019-03-12 15:44:40","logger":"root","caller":"(shell)","msg":{"a":"b"}}
```

**Comment by s-fleck** [comment]
Thanks for the comment! I think most of the questions you asked are already addressed by lgr, so it might be more of a problem of the documentation (which is still wip)

> As for me there should be clear separation between log destinations and log formatters (and it seems you generally share same idea). And from this perspective AppenderJson looks a little bit weird - it mixes both file sink and JSON formatting.

You are absolutely right. AppenderJSON is little more than a pre-configured wrapper for AppenderFile with LayoutJson though. I did this because I want to push json logging and make configuration a bit easier, i see how it might be confusing though... 

> For example with JSON layout we can serialize R objects into json objects (and have fully machine-readable logs)

Well you can already do that using "custom fields" (named arguments to the log function)
```
library(lgr)
lgr$appenders$console$set_layout(layout = LayoutJson$new())
lgr$info(list(a = 'b'))

lgr$info("message cannot be empty", a = "b")
# {"level":400,"timestamp":"2019-03-12 13:26:57","logger":"root","caller":"(shell)","msg":"message cannot be empty","a":"b"}
lgr$info("", data = list(a = "b"))
# {"level":400,"timestamp":"2019-03-12 13:27:03","logger":"root","caller":"(shell)","msg":"","data":{"a":"b"}}
```
 
Please let me know if this fully addresses your question/feature request.

**Comment by dselivanov** [comment]
Thats great, thanks a lot! indeed I've missed that from vignetter.

**Comment by s-fleck** [comment]
Note also that if you use AppenderBuffer or AppenderDt (for example) it even retains the unserialzed R object.
