### ISSUE TITLE
Supply preset configs

### ISSUE THREAD

**Issue by s-fleck** [s-fleck/lgr#20]
Better default config for the root logger, and enable the user to be able to load configs from `options()` and/or environment variables.

lgr should also include some presets with documentation, fe:

* minimal
* memory

**Comment by s-fleck** [comment]
@mllg I managed to get around to it today and just removed AppenderDt from the root logger. Together with your suggestion to suspend logging, you can now also set the default log level via an environment variable, and load a logger configuration file (that you can also specify via an environemt variable) (see ?lgr).

If you get around to testing it a bit, i'm always open to feedback. Sadly the config files are not really documentet yet, but it should be pretty straight forward (look at inst/configs for example YAMLs)

**Comment by mllg** [comment]
I've not tried the yaml config, but the environment variables seem to work just fine.

**Comment by s-fleck** [comment]
Close. Rather than preset configuration files we have `basic_config()`.
