### ISSUE TITLE
Remove AppenderDt from the root logger?

### ISSUE THREAD

**Issue by mllg** [s-fleck/lgr#22]
I really like AppenderDt and how easy it is to retrieve the logged objects for further inspections. However, I wonder if it is the best idea to have AppenderDt in the root logger. I am a bit concerned here about the memory consumption, especially for longer R sessions or when dealing with large R objects. 

Wouldn't it make more sense to remove it from the root logger, and only active it for debugging?

**Comment by s-fleck** [comment]
The appender will likely go from the default config in the next version. In general the default config is a bit to complex at the moment I think. I will instead supply a few example configurations with descriptions, but im still trying to work out the details.

Memory is not really an issue though. The whole data.table gets preallocated at the beginning and does not grow for long sessions. I don't remember how much memory it uses, but i benchmarked it back then and it should be less than 10mb. (caveat: if you heavily use the custom fields feature the memory used by the log can still grow)

**Comment by dselivanov** [comment]
I also think data table appender should not be configured by default.

ср, 3 апр. 2019 г., 14:19 Stefan Fleck <notifications@github.com>:

**Comment by s-fleck** [comment]
thanks for all your inputs!
 You are right @dselivanov ... it's there for historical reasons mainly. When I started working on lgr it was built around an in memory data.table before I switched to a design that contained the LogEvent S6 class.

The next update will feature a much more minimal (and hopefully easier to understand) default config for the root logger.

**Comment by s-fleck** [comment]
@mllg I managed to get around to it today and just removed AppenderDt from the root logger. Together with your suggestion to suspend logging, you can now also set the default log level via an environment variable, and load a logger configuration file (that you can also specify via an environemt variable) (see ?lgr).

If you get around to testing it a bit, i'm always open to feedback. Sadly the config files are not really documentet yet, but it should be pretty straight forward (look at inst/configs for example YAMLs)

**Comment by s-fleck** [comment]
Related to #20
