### ISSUE TITLE
Syslog appender

### ISSUE THREAD

**Issue by atheriel** [s-fleck/lgr#26]
Hey, I'm the author of the [**rsyslog**](https://github.com/atheriel/rsyslog) package. I'm wondering if you're interested in including a syslog appender. If so, I'd be happy to write it.

**Comment by s-fleck** [comment]
Yes, if you could draw up a pull request that would be great! A syslog appender is on my mental todo list for a while, but since I don't use syslog myself I didn't get around to it yet. I didn't really write any real developer documentation yet, so if any questions arise, don't hesitate to ask!
