### ISSUE TITLE
Dependency on isFALSE 

### ISSUE THREAD

**Issue by luke-a** [s-fleck/lgr#32]
Hi there,

package installation currently seems to depend on R v3.5 because somewhere `isFLASE` is used, which has been introduced with 3.5. Can you remove the dependency, as discussed e.g. [here](https://github.com/r-spatial/mapview/issues/177), too?

**Comment by s-fleck** [comment]
Yes I can remove that dependency; however, it will take me a while to get the next lgr version ready for CRAN. If you have lgr as a dependency for a package and it is urgent, I can consider pushing a hotfix though.

**Comment by luke-a** [comment]
Thanks @s-fleck , and no urgency. Just wanted to make a note, because my package installation for the latest version failed. 
Have a nice weekend.

**Comment by s-fleck** [comment]
Ok thx :)

The `isFALSE()` dependency is just in `basic_config()`, which is an optional helper for simplifying logger configuration, so it's not a very critical part of the lgr package.

**Comment by lorenzwalthert** [comment]
Or use https://github.com/r-lib/backports to keep it, but maybe not worth for such a function only...

**Comment by mllg** [comment]
A hotfix release would be great, we are running into problems on our CI because of the missing `isFALSE()`.

**Comment by mllg** [comment]
Also note that you cannot install or load `lgr` for R < 3.5, `basic_config()` is called in `.onLoad()`.

**Comment by s-fleck** [comment]
yes sorry this bug was quite a (backwards compat) mess. should be fixed on github, but it still might take me a while to get the current lgr version on cran :/

**Comment by s-fleck** [comment]
The hotfix is on its way to CRAN (so might take a few days before it becomes available). I hope everything works now. Please comment once you tested it.
