### ISSUE TITLE
format timestamp in LayoutJson

### ISSUE THREAD

**Issue by asiripanich** [s-fleck/lgr#34]
Hi @s-fleck, thank you for creating this great logging package!

Is it possible to format timestamp in LayoutJson? for example if I want to include milisecond.

**Comment by s-fleck** [comment]
it's not possible directly but there are some hackish ways to get it done. I'll do a writeup for you but it will take a few days as I'm currently traveling.

**Comment by asiripanich** [comment]
Thanks!

**Comment by s-fleck** [comment]
So there are two recommended ways to do this: The first variant is slightly shorter but more dangerous, the second is safer but more verbose,

```
library(lgr)

a <- lgr::AppenderJson$new(tempfile())
  
a$add_filter(function(event){
  event$timestamp_subsec <- format(event$timestamp, "%H:%M:%S:%OS") # event is modified by reference
  TRUE # must return TRUE otherwise the event is discarded!
})
  
lg <- get_logger("test")
lg$add_appender(a, name = "json")               

lg$fatal("test")
lg$appenders$json$show()
```

This has the side effect of permanently modifying the log event, i.e. if you have several appenders, all appenders after your Json appender will also have the timestamp_subsec field. btw you can just overwrite the existing `timestamp` field of the log event, but this WILL cause problems if you are using several appenders.

A second, slightly safer variant is just creating your own layout
```
myLayoutJson <- R6::R6Class(
  "myJsonAppender",
  inherit = lgr::LayoutJson,
  public = list(
    format_event = function(event) {
      x <- event$values
      x$timestamp <- format(x$timestamp, "%H:%M:%S.%OS")
      
      do.call(
        jsonlite::toJSON,
        args = c(list(x = x), get(".toJSON_args", private))
      )
    }
  )
)


a <- AppenderFile$new(
  file = tempfile(),
  layout = myLayoutJson$new()
)

lg <- get_logger("test")
lg$add_appender(a, name = "json2")
lg$fatal("test")
lg$appenders$json2$show()

```

**Comment by s-fleck** [comment]
Usually if you want some custom solution in lgr you just need to subclass something and overwrite a single function such as `format_event()` in this case. I should probably write some tutorials on this at some point, but at the moment I am lacking the time :(

**Comment by asiripanich** [comment]
I see. Thank you for spending your time to write the solutions. Any chance u would make the json appender more flexible in its format rather than using a custom solution? :)

**Comment by s-fleck** [comment]
I guess it's a useful feature. I'll keep it in mind and leave this issue open. Might take a bit though

**Comment by asiripanich** [comment]
Great! I actually want to contribute this but I cant promise anything yet. I will let u know if I get around to it.

**Comment by s-fleck** [comment]
I ended up implementing the feature now. If you are using the github version of lgr feel free to test it :)
