### ISSUE TITLE
Integration with progress bar packages

### ISSUE THREAD

**Issue by Fuco1** [s-fleck/lgr#37]
Is there any possibility of integration with progress bar packages such as progressr or others?  It would be nice to have a global control of all the output and the log levels provide this functionality very clearly.

However I'm not sure how it would work in practice or if it is even feasable.

**Comment by s-fleck** [comment]
Thanks for the suggestion, but i think this is not really possible within the scope of lgr. If you wanted to tie displaying of progress bars in your package to the threshold of the lgr root logger you could do something like:

```
with_lgr_progress <- function(){
  if (lgr::lgr$threshold >= lgr::get_log_levels("info")){
    prog <- progressr::with_progress
  } else {
    prog <- progressr::without_progress
  }
  prog()
}

with_lgr_progress()({...your code here...})
```
With some trickery you can also turn with_lgr_progress into an active binding inside your package, to get rid of the extra `()` (see ?makeActiveBinding())`, but this probably just makes it *more* confusing.

A cleaner solution would to tie the progress bars to all Appenders that write to the console, but you should not make assumptions about how your user will configure lgr appenders, so this is not really fesible.

**Comment by Fuco1** [comment]
Thanks, the example you provided is something along the lines I was thinking.  Probably makes no sense to print a progress to a json appender or a file anyway, so yea this is not really feasible to put inside a package.  But in my "script" code this is exactly what I wanted, so I can quickly turn it on/off for production/debugging.

Cheers!
