### ISSUE TITLE
AppenderFileRotatingDate does not genereate a timestamped file.

### ISSUE THREAD

**Issue by sossaman** [s-fleck/lgr#39]
Hello,
it seems that the creation of timestamped file through AppenderFileRotatingDate does not work.
A file is created but without the date in its name.

**Comment by s-fleck** [comment]
Hmm the timestamp will only be added to the rotated files. AppenderFileRotatingDate is supposed to work like this:

1. log to xyz.log 
2. log file exceeds `age` or `size` -> xyz.log gets renamed to xyz.2020-11-25.log 
3. AppenderFileRotatingDate continues logging to the (now empty) xyz.log

This is not working for you?

**Comment by sossaman** [comment]
Thanks for the clarification, but unfortunately it still does not `seem` to work. The rotated file also does not contain any date, it has simply added a .1 added to the name.
Anyway this is the code I have used to test it:
logfile <- paste(u, "/Log/Monitoring", ".log",  sep = "")
# u is a path!

lg <- get_logger("CMLogger")$
    set_propagate(FALSE)$
    set_appenders(list(rotating = AppenderFileRotatingDate$new(
        file = logfile,
        layout = LayoutJson$new(),
        age = Inf, 
        size = -1,
        max_backups = 2,
        backup_dir = paste(u,"/Log/Bkp", sep = ""),
        fmt = "%Y-%m-%d",
        create_file = TRUE,
        overwrite = FALSE,
        compression = TRUE,
        threshold = 300L)
    ))

**Comment by s-fleck** [comment]
Okay there is definitley something wrong, I'll try to fix it ASAP

**Comment by s-fleck** [comment]
So there was a bug in rotor when it came to the `max_backups` argument. Please try again, but install the dev version of rotor from www.github.com/s-fleck/rotor first (`remotes::install_github("s-fleck/rotor")`

also you probably want `age = -1` instead of `age = inf`  (`age = inf` means "never rotate"). I should probably rethink the default value here, or at least throw a warning in lgr.

**Comment by sossaman** [comment]
Thanks, the problem seems to be fixed now.
