### ISSUE TITLE
TESTS: Drop test with 'transparent' futures

### ISSUE THREAD

**Issue by HenrikBengtsson** [s-fleck/lgr#43]
Hi.  As part of taking the **future** package to the next level, I'm narrowing down what futures may do.  This is mostly backward compatible, but one thing that needs to go is the support for `future(..., local = FALSE)`.  Most of this has already been done, cf. https://github.com/HenrikBengtsson/future/issues/382.  However, it is still used internally by `transparent` futures, which I'll keep supporting for a while, but they should only be used for debugging and troubleshooting purposes. They should never for production use  The reason for this is that `local = FALSE` introduces behavior that is an outlier in the future framework.   (This will be clarified further in the next release of **future**).

I spotted that **lgr** uses 'transparent' futures in one of its package tests:

https://github.com/s-fleck/lgr/blob/2c66dce6036f41637c8336e314654901f8455c74/tests/testthat/test_parallel.R#L1-L8

Could you please drop `"transparent"` from your checks?  It is so similar to `"sequential"`, which should be sufficient for your tests anyway.

While at it, you could also drop that `# "multiprocess"` line, because that is already formally deprecated.

**Comment by s-fleck** [comment]
No Problem! Do you need it before the next release of futures? It"s an easy fix, but I'm working out some other details in lgr right now that I would like to finish before the next CRAN release ... but if it's urgent I can prioritze it.

**Comment by HenrikBengtsson** [comment]
No rush. Thxs
