### ISSUE TITLE
should default Layout(s) recognize conditions?

### ISSUE THREAD

**Issue by mmuurr** [s-fleck/lgr#45]
One common pattern of mine (and likely others?) is:
```r
tryCatch({
  ## do something
}, error = function(e) {
  lgr$error(conditionMessage(e))
  ## perhaps some error-handling
})
```
Would it be worth it for the common default Layout(s) to recognize objects inheriting from `condition` and simply extract the `conditionMessage`?, so `lgr$error(conditionMessage(e))` can be simplified to `lgr$error(e)`?

The answer might be "no" (which is perfectly acceptable), but I thought it might be useful to suggest this for discussion anyhow.
I also realize I can just extend the various Layout R6 classes and implement this, but again, worth asking :-)

**Comment by s-fleck** [comment]
Thanks for the suggestions. There were some ways to directly log error conditions in older versions of lgr, but I removed them because I was not really happy with the solution. Detecting error conditions directly in `$log()` & co seems like a good Idea, i'll evaluate it :)

**Comment by s-fleck** [comment]
So I implemented this directly in `$log()`, not in the Layouts. If you now supply an error condition as the message argument, they are automatically unpacked. If you supply them as named argument, they are still not processed though.

```
e <- errorCondition("foobar")

lgr::lgr$fatal(e)
lgr::lgr$fatal("ohno", conditon = e)
```
