### ISSUE TITLE
No logging at 'trace' and 'debug' level

### ISSUE THREAD

**Issue by sn0001** [s-fleck/lgr#68]
The root logger does not return a console message with `lgr$trace()` or `lgr$debug()`. This is also the case with `lgr$log(level = "trace/debug")`. Similarly, file appenders produce no output at these levels.

Minimal reproducible example:

```
library(lgr)
lgr$trace("test")
lgr$debug("test")
lgr$log(level = "trace", "test")
lgr$log(level = "debug", "test")
lgr$info("test") # this works
```

**Comment by s-fleck** [comment]
I am 99% sure this is a configuration issue. Please note that appenders _also_ have a logging threshold. 

if you just run `lgr::get_logger()` you'll see the root logger and the threshold of all appenders. eg:

```
lg <- lgr::get_logger()
print(lg)

# you'll probably see something like this:
#> <LoggerRoot> [info] root
#>
#> appenders:
#>  console: <AppenderConsole> [info] -> console

# you can then just do 
lg$appenders$console$set_threshold("trace") 
# or
lg$appenders$console$set_threshold(NA) 
```

Note: `NA` means log everyhing, `"trace"` means log everything trace or higher. for practical purposes, this is equivalent

**Comment by sn0001** [comment]
Dear

**Comment by sn0001** [comment]
Thanks for your quick reply!

Looking at `basic_config()`, I get:
```
<LoggerRoot> [info] root

appenders:
  console: <AppenderConsole> [all] -> console
```

Thus, when I instantiate a new logger `lg` with `lgr::get_logger()`, it should log trace and debug levels:
```
> lg <- lgr::get_logger()
> print(lg)
<LoggerRoot> [info] root

appenders:
  console: <AppenderConsole> [all] -> console
```

But even if I do `lg$appenders$console$set_threshold("trace")`, it will not respond to a call like `lg$trace("test")`.

**Comment by s-fleck** [comment]
but this looks like your logger itself is just configured for `info`!

```lg$set_threshold("trace")```

**Comment by sn0001** [comment]
Yes, this did the trick! Obviously, I overlooked that. Thanks @s-fleck for your support!
