### ISSUE TITLE
lgr$fatal does not exit

### ISSUE THREAD

**Issue by fgvieira** [s-fleck/lgr#69]
After I call 
```
lgr$fatal("Fatal error!")
```
The script keeps running. Shouldn't it quit immediately after `fatal`?

If not, what is the intended difference between `critical` and `fatal`?

**Comment by s-fleck** [comment]
`critical` does not exist in lgr. Anyways lgr will always just log, not exit the program! that's beyond it's scope.

you can do something like

```
msg <- lg$fatal("everything is bad")
stop(msg)
```

`stop(lg$fatal("everything is bad")`  will also work, but the caller information in the log event will be less useful

**Comment by fgvieira** [comment]
Thanks for the lightning fast response! I mean `error` and `fatal`.

**Comment by s-fleck** [comment]
Depending on your usecase, you will not need all 5 log levels. Your probably fine with just using info, warning and error!
For more complex applications you might want some more differntiation.

Eg assume you are making a plumber API. `fatal` would men your API crashed, `error` would just be some function threw an unexpected error. But it's really up to you to assign meaning to each level you are using :)
